//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartotekaApp.Models
{
    using CartotekaApp.Domain;
    using System;
    using System.Collections.Generic;
    
    public partial class Order : ObservableObject
    {
        private int _orderYear;
        private decimal _price;
        private int _units;

        public int Id { get; set; }
        public int BookId { get; set; }
        public int OrderYear
        {
            get => _orderYear;
            set => SetProperty(ref _orderYear, value);
        }
        public decimal Price
        {
            get => _price;
            set => SetProperty(ref _price, value);
        }
        public int Units
        {
            get => _units;
            set => SetProperty<int>(ref _units, value);
        }

        public virtual Book Book { get; set; }
    }
}
