//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;

namespace CartotekaApp.Models
{
    public interface ICartotekaDbContext
    {
        DbSet<Author> Authors { get; set; }
        DbSet<Book> Books { get; set; }
        DbSet<Category> Categories { get; set; }
        DbSet<Group> Groups { get; set; }
        DbSet<Keyword> Keywords { get; set; }
        DbSet<Order> Orders { get; set; }
        DbSet<Role> Roles { get; set; }
        DbSet<User> Users { get; set; }

        int SaveChanges();
    }
}